travis:
  secure:
    BINSTAR_TOKEN: m2ujxr8YDm/yeo5xarMoY0dTiIoCY6YAQaM1SLENCHq2Ae6wC2kScy6+3hIJ5WVfvKFB9p7nm6qqNNnRSznP7kX9+bAw353F2V5BKce1a2i6lTF5Oef3620nmcfOTqqYyD89g9LpEtiyVMeWpWL1z9btWv1QzdQj+IFT+EYrAl5IK97w8ZXFKXi2FNK6ndXpuCcdcLMy479JwZwWnJjFE2QviVLqV52xhjDKiXDrQPX1oXj84tzOVu9b4Ggeo2VtoSxsbkGRfw/a716sYlonMZwRdu96mPsnq6GW8EvFUL/nZIjpz7f+7fPtqtoIGNS0Zf6BTJjTWyOLhiwW3xNQJtvuvJOHDLMeB2N3kfB67ypWifnUk/fsbv56QUqulg5xXAKgqEva6rZ5d4Ht8jCHPC+FWqFtIcHBSpJRRWlbkfRlfMe2UFfgK9A42pQTdj4QhMvWbESYaWHN1iHCD+qpew5kP/PgGer0LbBvaU+T0XForPBiO4uiJkC7RlORpDDaY7EcSEQLqTQTk7blwcxTboH/tWrhxzI7ZklELbgrtOsuvCI07k+BfSH0jsxAF4xeQhPnmqMr7S92K1uAxdgJTvvbQuzyZMvgKz0h9Bf5FQUkiPgzRSDXYM1rGjsVYoCtgDY+DfhsYSi9eug84YDVYNYe6bRxrpZDQYMUzAzNMrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
